### ISSUE TITLE
Save 1 byte :-)

### ISSUE THREAD

**Issue by peterdell** [dmsc/zx0-6502#1]
By using X instead of Y for the initialization, you can save one byte as zp,y is actually abs,y.

```
              ; Get initialization block
              ldx #7

copy_init     lda zx0_ini_block-1, x
              sta offset-1, x
              dey
              bne copy_init
```

**Comment by dmsc** [comment]
Hi!

Sadly, you need Y=0 in the rest of the code, so you need 2 extra bytes for the "LDY #0" :-)

One alternative would be to use LDA (ZP,X) with X=0 instead of LDA (ZP),Y with Y=0 in the rest of the code, and replace all TAX/DEX with TAY/DEY, but that will make the code slower.

Also, if you want smaller decompresor size, look at my ZX02 at https://github.com/dmsc/zx02/ , it is a simpler and smaller variant for the 6502.
